#!/bin/sh


set -e

#DEBHELPER#

case "$1" in
    configure)
    /usr/bin/mastermind_deploy.sh `/usr/bin/mastermind_app_name.sh` ||true
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
