#!/usr/bin/python

from time import sleep
from opster import command, dispatch
from cocaine.client import Client
import msgpack

@command()
def collect(config=('c', 'cocaine_config.json', 'Path to cocaine dealer config')):
    '''Force balancer to collect groups info'''
    c = Client(config)
    sleep(1)

    res = c.get('mastermind/collect')
    if isinstance(res, list) and len(res) > 0:
        print msgpack.unpackb(res[0])

@command()
def bad_groups(config=('c', 'cocaine_config.json', 'Path to cocaine dealer config')):
    '''Get list of broken symmetric groups from balancer'''
    c = Client(config)
    sleep(1)

    res = c.get('mastermind/get_bad_groups')
    print msgpack.unpackb(res[0])


@command()
def symmetric_groups(config=('c', 'cocaine_config.json', 'Path to cocaine dealer config')):
    '''Get list of symmetric groups from balancer'''
    c = Client(config)
    sleep(1)

    res = c.get('mastermind/get_symmetric_groups', 0)
    print msgpack.unpackb(res[0])

@command()
def uncoupled_groups(config=('c', 'cocaine_config.json', 'Path to cocaine dealer config')):
    '''Get list of uncoupled groups from balancer'''
    c = Client(config)
    sleep(1)

    res = c.get('mastermind/get_empty_groups', 0)
    print msgpack.unpackb(res[0])

@command()
def repair_groups(
            group,
            config=('c', 'cocaine_config.json', 'Path to cocaine dealer config')):
    '''Repair broken symmetric groups'''
    c = Client(config)
    sleep(1)

    group = int(group)
    res = c.get('mastermind/repair_groups', group)
    print msgpack.unpackb(res[0])

@command()
def group_info(
            group,
            config=('c', 'cocaine_config.json', 'Path to cocaine dealer config')):
    '''Get group info'''
    c = Client(config)
    sleep(1)

    group = int(group)
    res = c.get('mastermind/get_group_info', group)
    print msgpack.unpackb(res[0])

@command()
def balance(
            size,
            config=('c', 'cocaine_config.json', 'Path to cocaine dealer config')):
    '''Get group info'''
    c = Client(config)
    sleep(1)

    size = int(size)
    id = [0] * 64
    res = c.get('mastermind/balance', (size, 1, id))
    print msgpack.unpackb(res[0])

@command()
def couple_groups(
            size,
            config=('c', 'cocaine_config.json', 'Path to cocaine dealer config')):
    '''Make a couple of groups, number of groups is an argument'''
    c = Client(config)
    sleep(1)

    size = int(size)
    res = c.get('mastermind/couple_groups', size)
    print msgpack.unpackb(res[0])

@command()
def next_group_number(
            count,
            config=('c', 'cocaine_config.json', 'Path to cocaine dealer config')):
    '''Get unused group numbers, number of groups is an argument'''
    c = Client(config)
    sleep(1)

    count = int(count)
    res = c.get('mastermind/get_next_group_number', count)
    print msgpack.unpackb(res[0])


if __name__ == '__main__':
    dispatch()
