# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mmc

import flatbuffers

class LrcSettings(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsLrcSettings(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LrcSettings()
        x.Init(buf, n + offset)
        return x

    # LrcSettings
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LrcSettings
    def PartSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LrcSettings
    def Scheme(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return ""

def LrcSettingsStart(builder): builder.StartObject(2)
def LrcSettingsAddPartSize(builder, partSize): builder.PrependUint32Slot(0, partSize, 0)
def LrcSettingsAddScheme(builder, scheme): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(scheme), 0)
def LrcSettingsEnd(builder): return builder.EndObject()
