# automatically generated by the FlatBuffers compiler, do not modify

# namespace: mmc

import flatbuffers

class NativeSettings(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsNativeSettings(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NativeSettings()
        x.Init(buf, n + offset)
        return x

    # NativeSettings
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def NativeSettingsStart(builder): builder.StartObject(0)
def NativeSettingsEnd(builder): return builder.EndObject()
